name: Projeto DevOps

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: juniorhervis
        password: dinossauromorto1

    - name: Build Docker image
      run: docker build -t juniorhervis/devops:latest .

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: juniorhervis/devops:latest

    - name: Expose image with ngrok
      run: |
        docker run -d --name ngrok --rm -p 4040:4040 juniorhervis/devops:latest ngrok http 3000
        sleep 5 # Espera 5 segundos para o ngrok iniciar
        curl --silent --show-error http://localhost:4040/api/tunnels | grep -o "http://.*ngrok.io"


# jobs:
#   build-job:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Pull Docker image from Docker Hub
#       run: docker pull juniorhervis/devops:latest
#     - name: Run docker container
#       run: docker run -p 3000:3000 juniorhervis/devops:latest

#   teste-job:
#     needs: build-job
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: AppThreat/sast-scan-action@master

#   deploy-job:
#     needs: teste-job
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Ngrok Tunnel Action
#         uses: LuisBoto/ngrok-tunnel-action@v0.1.7.2
#         with:        
#           tunnel_type: http          
#           port: 3000          
#           save_url_to_filename: 'url.txt'          
#           ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}

