
name: Projeto DevOps

on:
  push:
   branches: [master]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
    - name: Pull Docker image from Docker Hub
      run: docker pull ${{ secrets.USER_DOCKER_HUB }} /${{ secrets.REPO }}:${{ secrets.TAG }}
    - name: Run container
      run: docker build -t ${{ secrets.USER_DOCKER_HUB }} /${{ secrets.REPO }}:${{ secrets.TAG }}

  teste-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: AppThreat/sast-scan-action@master
      
  deploy-job:
    needs: teste-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo Hello World
      - run: ngrok http 3000